name: CI

on:
  push:
    branches-ignore:
      - release
    tags-ignore:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci # Install dependencies.
      - run: npm run ci # Execute CI scripts.
      - run: git diff --exit-code # Fail if CI scripts make any source changes.

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci # Install dependencies.
      - run: npm run build # Build javascript.
      - run: npm run package # Build action package.
      - uses: ./
        with: # Exercise custom inputs.
          version: 2.7.0
          arguments: '--version'

  release:
    if: github.ref == 'refs/heads/main'
    needs: [ build, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: configure git
        run: |
          git config --global user.name jrouly
          git config --global user.email michel@rouly.net
      - run: |
          git checkout release
          git merge main
      - run: |
          npm ci
          npm run build
          npm run package
      - run: |
          git add lib dist
          git commit --allow-empty -m 'build new action package'
          git push origin release
